# Generated by Django 3.2.9 on 2021-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Begin', models.DateField(max_length=200, verbose_name='Fecha inicio')),
                ('End', models.DateField(max_length=200, verbose_name='Fecha entrega')),
                ('Advance', models.FloatField(max_length=200, verbose_name='Anticipo')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
            },
        ),
    ]
