# Generated by Django 3.2.9 on 2021-11-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_produccion_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='muebles',
        ),
    ]
