# Generated by Django 3.2.9 on 2021-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='muebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.FloatField(max_length=200, verbose_name='Precio')),
                ('lenght', models.FloatField(max_length=200, verbose_name='Largo')),
                ('width', models.FloatField(max_length=200, verbose_name='Ancho')),
                ('height', models.FloatField(max_length=200, verbose_name='Alto')),
                ('status', models.CharField(max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mueble',
                'verbose_name_plural': 'Muebles',
            },
        ),
    ]
