# Generated by Django 3.2.9 on 2021-11-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muebles',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('P', 'En producción'), ('E', 'Entregado')], max_length=200, verbose_name='Estado'),
        ),
    ]
