# Generated by Django 3.2.9 on 2021-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0004_alter_muebles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muebles',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
