# Generated by Django 3.2.9 on 2021-11-12 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('muebles', '0005_alter_muebles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='muebles',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
