# Generated by Django 3.2.9 on 2021-11-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('muebles', '0006_muebles_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='muebles',
            name='produccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion'),
        ),
    ]
