# Generated by Django 3.2.9 on 2021-11-12 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_remove_produccion_muebles'),
        ('muebles', '0008_remove_muebles_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='muebles',
            name='produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion'),
        ),
    ]
